version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: spring_pjc_2025_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root_pwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio_storage
    restart: always
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: mudarSenha@123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

  app:
    build: .
    container_name: spring_pjc_2025_app
    restart: always
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring_pjc_2025_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root_pwd
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: ROOTUSER
      MINIO_SECRET_KEY: mudarSenha@123
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  minio_data:
