-- Generated by the database client.
CREATE TABLE pessoa(
    pes_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    pes_data_nascimento date,
    pes_mae varchar(200) NOT NULL,
    pes_nome varchar(200) NOT NULL,
    pes_pai varchar(200),
    pes_sexo varchar(10) NOT NULL,
    PRIMARY KEY(pes_id)
);
CREATE UNIQUE INDEX ukocylhib9rg64809e1o9li94so ON pessoa USING btree ("pes_nome");